/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef RELATIVISTIC_BW
#define RELATIVISTIC_BW

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RelativisticBW : public RooAbsPdf {
public:
  RelativisticBW() {} ; 
  RelativisticBW(const char *name, const char *title,
	      RooAbsReal& _x,
                 RooAbsReal& _mH,
                 RooAbsReal& _w_fr,
                 RooAbsReal& _a0acc,
                 RooAbsReal& _a1acc,
                 RooAbsReal& _a2acc,
                 RooAbsReal& _a3acc
                 );
  RelativisticBW(const RelativisticBW& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RelativisticBW(*this,newname); }
  inline virtual ~RelativisticBW() { }

protected:

  RooRealProxy x ;
  RooRealProxy mH ;
  RooRealProxy w_fr ;
  RooRealProxy a0acc ;
  RooRealProxy a1acc ;
  RooRealProxy a2acc ;
  RooRealProxy a3acc ;

  Double_t evaluate() const ;

private:

  ClassDef(RelativisticBW,1) // Your description goes here...
};

#endif
