/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOGRAVITONRBWPDF
#define ROOGRAVITONRBWPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooGravitonRBWPdf : public RooAbsPdf
{
public:
    RooGravitonRBWPdf(){};
    RooGravitonRBWPdf(const char *name, const char *title,
                      RooAbsReal &_x,
                      RooAbsReal &_m,
                      RooAbsReal &_g);
    RooGravitonRBWPdf(const RooGravitonRBWPdf &other, const char *name = 0);
    virtual TObject *clone(const char *newname) const { return new RooGravitonRBWPdf(*this, newname); }
    inline virtual ~RooGravitonRBWPdf() {}

protected:
    RooRealProxy x;
    RooRealProxy m;
    RooRealProxy g;

    Double_t evaluate() const;
    Double_t L_gg(Double_t x) const;

private:
    ClassDef(RooGravitonRBWPdf, 1) // Your description goes here...
};

#endif
